version: '3'

services:
  bot:
    build: "."
    depends_on:
      - postgres
    volumes:
      - ./modules:/usr/src/app/modules
      - ./config.yml:/usr/src/app/config.yml

  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRESS_USER: postgres
      POSTGRES_DB: discord_bot
    volumes:
      - database:/var/lib/postgresql/data
    ports:
    - 5432:5432

volumes:
  database:
    external: false